### ISSUE TITLE
Check links in EJS

### ISSUE THREAD

**Issue by andiedoescode** [HattieTavares/mood-journal#17]
Make sure links on pages are accessing correct routes.

**Comment by fakehouseplant** [comment]
Specifically, the logout button and the check in link in dashboard.ejs need to be updated

**Comment by cynthiablack** [comment]
Updated dashboard.ejs to include links; tested & working in Chrome on MacOS.

**Comment by emmebravo** [comment]
@cynthiablack did you create a PR for this issue? Is this issue close then?

**Comment by cynthiablack** [comment]
@emmebravo It works on my machine & the PR with links was merged. It wasn't clear if it was working for everyone, though.
